// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    javaSidebar: [
        {
            type: 'category',
            label: 'Java Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/java'
                }
            ],
        }
    ],
    javaScriptSidebar: [
        {
            type: 'category',
            label: 'JavaScript Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/javascript'
                }
            ],
        },
    ],
    pythonSidebar: [
        {
            type: 'category',
            label: 'Python Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/python'
                }
            ],
        }
    ],
    cSidebar: [
        {
            type: 'category',
            label: 'C Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/c',
                }
            ],
        }
    ],

    cppSidebar: [
        {
            type: 'category',
            label: 'C++ Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/cpp'
                }
            ],
        }
    ],

    goSidebar: [
        {
            type: 'category',
            label: 'Go Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/go'
                }
            ],
        }
    ],

    rustSidebar: [
        {
            type: 'category',
            label: 'Rust Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/rust'
                }
            ],
        }
    ],

    sqlSidebar: [
        {
            type: 'category',
            label: 'SQL Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/sql'
                }
            ],
        }
    ],

    phpSidebar: [
        {
            type: 'category',
            label: 'PHP Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/php'
                }
            ],
        }
    ],
    cSharpSidebar: [
        {
            type: 'category',
            label: 'C# Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/c-sharp'
                }
            ],
        }
    ],

    kotlinSidebar: [
        {
            type: 'category',
            label: 'Kotlin Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/kotlin'
                }
            ],
        }
    ],
    swiftSidebar: [
        {
            type: 'category',
            label: 'Swift Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/swift'
                }
            ],
        }
    ],
    djangoSidebar: [
        {
            type: 'category',
            label: 'Django Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/django'
                }
            ],
        }
    ],
    angularSidebar: [
        {
            type: 'category',
            label: 'Angular Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/angular'
                }
            ],
        }
    ],
    expressSidebar: [
        {
            type: 'category',
            label: 'Express Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/express'
                }
            ],
        }
    ],
    fastApiSidebar: [
        {
            type: 'category',
            label: 'FastAPI Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/fastapi'
                }
            ],
        }
    ],
    flaskSidebar: [
        {
            type: 'category',
            label: 'Flask Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/flask'
                }
            ],
        }
    ],
    springSidebar: [
        {
            type: 'category',
            label: 'Spring Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/spring'
                }
            ],
        }
    ],
    pandasSidebar: [
        {
            type: 'category',
            label: 'Pandas Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'library/pandas'
                }
            ],
        }
    ],
    ginSidebar: [
        {
            type: 'category',
            label: 'Gin Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/gin'
                }
            ],
        }
    ],
    nextjsSidebar: [
        {
            type: 'category',
            label: 'Next.js Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/nextjs'
                }
            ],
        }
    ],
    pytorchSidebar: [
        {
            type: 'category',
            label: 'PyTorch Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'library/pytorch'
                }
            ],
        }
    ],
    tensorflowSidebar: [
        {
            type: 'category',
            label: 'TensorFlow Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'library/tensorflow'
                }
            ],
        }
    ],

    echoSidebar: [
        {
            type: 'category',
            label: 'Echo Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/echo'
                }
            ],
        }
    ],
    dotnetSidebar: [
        {
            type: 'category',
            label: '.NET Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/dotnet'
                }
            ],
        }
    ],
    algorithmSidebar: [
        {
            type: 'category',
            label: 'Data Structure & Algorithm Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'fundamental/algorithm'
                }
            ],
        }
    ],
    networksSidebar: [
        {
            type: 'category',
            label: 'Computer Networks Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/network'}
            ],
        }
    ],
    reactSidebar: [
        {
            type: 'category',
            label: 'React Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/react'
                }
            ],
        }
    ],

    vueSidebar: [
        {
            type: 'category',
            label: 'Vue.js Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/vue'
                }
            ],
        }
    ],
    wordpressSidebar: [
        {
            type: 'category',
            label: 'WordPress Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/wordpress'
                }
            ],
        }
    ],
    kongSidebar: [
        {
            type: 'category',
            label: 'Kong Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/kong'
                }
            ],
        }
    ],
    redisSidebar: [
        {
            type: 'category',
            label: 'Redis Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/redis'
                }
            ],
        }
    ],
    typescriptSidebar: [
        {
            type: 'category',
            label: 'TypeScript Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/typescript'
                }
            ],
        }
    ],
    mysqlSidebar: [
        {
            type: 'category',
            label: 'MySQL Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/mysql'
                }
            ],
        }
    ],
    postgresqlSidebar: [
        {
            type: 'category',
            label: 'PostgreSQL Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/postgresql'
                }
            ],
        }
    ],
    mongodbSidebar: [
        {
            type: 'category',
            label: 'MongoDB Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/mongodb'
                }
            ],
        }
    ],
    kubernetesSidebar: [
        {
            type: 'category',
            label: 'Kubernetes Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/kubernetes'
                }
            ],
        }
    ],
    cicdSidebar: [
        {
            type: 'category',
            label: 'CI/CD Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/cicd'
                }
            ],
        }
    ],

    arduinoSidebar: [
        {
            type: 'category',
            label: 'Arduino Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'iot/arduino'
                }
            ],
        }
    ],
    stm32Sidebar: [
        {
            type: 'category',
            label: 'STM32 Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'iot/stm32'
                }
            ],
        }
    ],
    ubuntuSidebar: [
        {
            type: 'category',
            label: 'Ubuntu Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'os/ubuntu'
                }
            ],
        }
    ],
    dockerSidebar: [
        {
            type: 'category',
            label: 'Docker Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/docker'
                }
            ],
        }
    ],
    debianSidebar: [
        {
            type: 'category',
            label: 'Debian Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'os/debian'
                }
            ],
        }
    ],

    gitSidebar: [
        {
            type: 'category',
            label: 'Git Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/git'
                }
            ],
        }
    ],
    nginxSidebar: [
        {
            type: 'category',
            label: 'Nginx Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/nginx'
                }
            ],
        }
    ],

    ansibleSidebar: [
        {
            type: 'category',
            label: 'Ansible Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/ansible'
                }
            ],
        }
    ],
    rabbitmqSidebar: [
        {
            type: 'category',
            label: 'RabbitMQ Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'middleware/rabbitmq'}
            ],
        }
    ],

    interviewSidebar: [
        {
            type: 'category',
            label: 'Interview Preparation',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/interview'}
            ],
        }
    ],
    databaseSidebar: [
        {
            type: 'category',
            label: 'Database & Information System',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/database'}
            ],
        }
    ],
    osSidebar: [
        {
            type: 'category',
            label: 'Operating System',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/os'}
            ],
        }
    ],
    terraformSidebar: [
        {
            type: 'category',
            label: 'Terraform Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'devops/terraform'}
            ],
        }
    ],
    grafanaSidebar: [
        {
            type: 'category',
            label: 'Grafana Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/grafana'}
            ],
        }
    ],
    prometheusSidebar: [
        {
            type: 'category',
            label: 'Prometheus Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/prometheus'}
            ],
        }
    ],
    // alloySidebar: [
    //     {
    //         type: 'category',
    //         label: 'Alloy Tutorial',
    //         link: {
    //             type: 'generated-index',
    //         },
    //         collapsible: false,
    //         collapsed: false,
    //         items: [
    //             {type: 'autogenerated', dirName: 'observability/alloy'}
    //         ],
    //     }
    // ],
    // jaegerSidebar: [
    //     {
    //         type: 'category',
    //         label: 'Jaeger Tutorial',
    //         link: {
    //             type: 'generated-index',
    //         },
    //         collapsible: false,
    //         collapsed: false,
    //         items: [
    //             {type: 'autogenerated', dirName: 'observability/jaeger'}
    //         ],
    //     }
    // ],
    lokiSidebar: [
        {
            type: 'category',
            label: 'Loki Tutorial',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/loki'}
            ],
        }
    ],
    //
    // opentelemetrySidebar: [
    //     {
    //         type: 'category',
    //         label: 'OpenTelemetry Tutorial',
    //         link: {
    //             type: 'generated-index',
    //         },
    //         collapsible: false,
    //         collapsed: false,
    //         items: [
    //             {type: 'autogenerated', dirName: 'observability/opentelemetry'}
    //         ],
    //     }
    // ],
    //


    // pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
    // javaScriptSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
    // cSidebar: [{type: 'autogenerated', dirName: 'c'}],
    // cppSidebar: [{type: 'autogenerated', dirName: 'cpp'}],
    // goSidebar: [{type: 'autogenerated', dirName: 'go'}],
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
