import { cp, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const workspace = process.cwd();
const docsRoot = path.join(workspace, 'docs');
const publicAssetsRoot = path.join(workspace, 'public', 'docs-assets');

const domainTitles = {
  database: 'Databases',
  devops: 'DevOps',
  framework: 'Frameworks',
  fundamental: 'CS Fundamentals',
  iot: 'Internet of Things (IoT)',
  language: 'Programming Languages',
  library: 'Libraries',
  middleware: 'Middleware',
  observability: 'Observability',
  os: 'Operating Systems',
};

function displayName(name) {
  return name
    .replace(/^\d+[-_]/, '')
    .split(/[-_]/)
    .map((part) => {
      const known = {
        api: 'API',
        cicd: 'CI/CD',
        cpp: 'C++',
        css: 'CSS',
        devops: 'DevOps',
        dotnet: '.NET',
        html: 'HTML',
        iot: 'IoT',
        javascript: 'JavaScript',
        nextjs: 'Next.js',
        nginx: 'Nginx',
        os: 'OS',
        php: 'PHP',
        sql: 'SQL',
        typescript: 'TypeScript',
        vue: 'Vue.js',
      };
      return known[part.toLowerCase()] ?? `${part.charAt(0).toUpperCase()}${part.slice(1)}`;
    })
    .join(' ');
}

function compareDocusaurusOrder(left, right) {
  if (left === 'index') return -1;
  if (right === 'index') return 1;

  const leftNumber = /^(\d+)[-_]/.exec(left)?.[1];
  const rightNumber = /^(\d+)[-_]/.exec(right)?.[1];
  if (leftNumber !== undefined && rightNumber !== undefined) {
    const difference = Number(leftNumber) - Number(rightNumber);
    if (difference !== 0) return difference;
  } else if (leftNumber !== undefined) {
    return -1;
  } else if (rightNumber !== undefined) {
    return 1;
  }

  return left.localeCompare(right);
}

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(absolutePath)));
    else files.push(absolutePath);
  }
  return files;
}

function categorySlug(label) {
  return label
    .normalize('NFKD')
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, '')
    .replaceAll(' ', '-');
}

function findAutogeneratedDirectory(items) {
  for (const item of items ?? []) {
    if (item?.type === 'autogenerated') return item.dirName;
    const nested = findAutogeneratedDirectory(item?.items);
    if (nested) return nested;
  }
}

async function readSidebarConfiguration() {
  const source = await readFile(path.join(workspace, 'sidebars.js'), 'utf8');
  const titles = new Map();
  const legacyCategoryRoutes = {};
  const duplicateSlugs = new Map();
  const executableSource = source.replace(/export default sidebars;?/, 'return sidebars;');
  const sidebars = Function(executableSource)();

  for (const sidebar of Object.values(sidebars)) {
    const root = sidebar?.[0];
    const directory = findAutogeneratedDirectory(root?.items);
    if (!root?.label || !directory) continue;
    titles.set(directory, root.label);

    const baseSlug = categorySlug(root.label);
    const duplicateIndex = duplicateSlugs.get(baseSlug) ?? 0;
    duplicateSlugs.set(baseSlug, duplicateIndex + 1);
    const slug = duplicateIndex === 0 ? baseSlug : `${baseSlug}-${duplicateIndex}`;
    legacyCategoryRoutes[slug] = `/docs/${directory}`;
  }

  return { titles, legacyCategoryRoutes };
}

function contentAssetUrl(documentPath, relativeAsset) {
  const documentDirectory = path.dirname(path.relative(docsRoot, documentPath));
  const assetPath = path.normalize(path.join(documentDirectory, relativeAsset));
  return `/docs-assets/${assetPath.split(path.sep).join('/')}`;
}

function inferredDocumentTitle(documentPath, source) {
  const heading = /^#\s+(.+?)\s*#*\s*$/m.exec(source)?.[1];
  if (heading) {
    return heading
      .replace(/!?(?:\[([^\]]+)\])\([^)]*\)/g, '$1')
      .replace(/[*_`]/g, '')
      .trim();
  }

  return displayName(path.basename(documentPath, path.extname(documentPath)));
}

function ensureTitleFrontmatter(documentPath, source) {
  const frontmatter = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(source);
  const title = inferredDocumentTitle(documentPath, source);

  if (!frontmatter) return `---\ntitle: ${JSON.stringify(title)}\n---\n\n${source}`;
  if (/^title:\s*\S.*$/m.test(frontmatter[1])) return source;

  const replacement = frontmatter[0].replace(
    /^---\r?\n/,
    `---\ntitle: ${JSON.stringify(title)}\n`,
  );
  return `${replacement}${source.slice(frontmatter[0].length)}`;
}

async function writeFileIfChanged(file, content) {
  try {
    if ((await readFile(file, 'utf8')) === content) return false;
  } catch {
    // Missing generated files are created below.
  }
  await writeFile(file, content);
  return true;
}

function unwrapDocusaurusMdxCodeBlocks(source) {
  const lines = source.split(/(?<=\n)/);
  let insideWrapper = false;

  return lines
    .filter((line) => {
      if (/^```mdx-code-block\s*(?:\r?\n)?$/.test(line)) {
        insideWrapper = true;
        return false;
      }
      if (insideWrapper && /^```\s*(?:\r?\n)?$/.test(line)) {
        insideWrapper = false;
        return false;
      }
      return true;
    })
    .join('');
}

async function migrateDocuments(files) {
  let changedDocuments = 0;
  let copiedAssets = 0;

  for (const absolutePath of files) {
    const extension = path.extname(absolutePath);
    if (extension !== '.md' && extension !== '.mdx') {
      if (extension === '.json') continue;
      const relativePath = path.relative(docsRoot, absolutePath);
      const destination = path.join(publicAssetsRoot, relativePath);
      await mkdir(path.dirname(destination), { recursive: true });
      await cp(absolutePath, destination);
      copiedAssets += 1;
      continue;
    }

    const original = await readFile(absolutePath, 'utf8');
    let migrated = original;
    const hadDocusaurusImports = /^import\s+\w+\s+from\s+['"]@theme\//m.test(migrated);

    migrated = migrated.replace(
      /^import\s+(?:Tabs|TabItem|Image|Admonition|TOCInline)\s+from\s+['"]@theme\/[^'"]+['"];?\s*\n/gm,
      '',
    );
    migrated = unwrapDocusaurusMdxCodeBlocks(migrated);
    if (hadDocusaurusImports) {
      migrated = migrated.replace(/^import React from ['"]react['"];?\s*\n/m, '');
    }

    migrated = migrated.replace(
      /require\((['"])(\.\/?img\/[^'"]+)\1\)/g,
      (_match, _quote, relativeAsset) => JSON.stringify(contentAssetUrl(absolutePath, relativeAsset)),
    );
    migrated = migrated.replace(
      /(!\[[^\]]*\]\()((?:\.\.?\/)?img\/[^)\s]+)(\))/g,
      (_match, prefix, relativeAsset, suffix) =>
        `${prefix}${contentAssetUrl(absolutePath, relativeAsset)}${suffix}`,
    );
    migrated = migrated.replace(
      /(src=['"])((?:\.\.?\/)?img\/[^'"]+)(['"])/g,
      (_match, prefix, relativeAsset, suffix) =>
        `${prefix}${contentAssetUrl(absolutePath, relativeAsset)}${suffix}`,
    );
    migrated = ensureTitleFrontmatter(absolutePath, migrated);

    if (migrated !== original) {
      await writeFile(absolutePath, migrated);
      changedDocuments += 1;
    }
  }

  return { changedDocuments, copiedAssets };
}

async function generateMetadata(files, sidebarTitles) {
  const contentDirectories = new Set([docsRoot]);
  for (const file of files) {
    if (!['.md', '.mdx'].includes(path.extname(file))) continue;
    let current = path.dirname(file);
    while (current.startsWith(docsRoot)) {
      contentDirectories.add(current);
      if (current === docsRoot) break;
      current = path.dirname(current);
    }
  }

  let generated = 0;
  for (const directory of [...contentDirectories].sort()) {
    const relativeDirectory = path.relative(docsRoot, directory).split(path.sep).join('/');
    const entries = await readdir(directory, { withFileTypes: true });
    const pages = entries
      .filter((entry) => {
        if (entry.isDirectory()) return contentDirectories.has(path.join(directory, entry.name));
        return ['.md', '.mdx'].includes(path.extname(entry.name));
      })
      .map((entry) => (entry.isDirectory() ? entry.name : path.basename(entry.name, path.extname(entry.name))))
      .sort(compareDocusaurusOrder);

    const legacyCategoryPath = path.join(directory, '_category_.json');
    let legacyCategory = {};
    try {
      legacyCategory = JSON.parse(await readFile(legacyCategoryPath, 'utf8'));
    } catch {
      // Directories without Docusaurus category metadata use derived labels.
    }

    const segments = relativeDirectory ? relativeDirectory.split('/') : [];
    const isTopicRoot = segments.length === 2;
    const title =
      legacyCategory.label ??
      sidebarTitles.get(relativeDirectory) ??
      (segments.length === 1 ? domainTitles[segments[0]] : undefined) ??
      (relativeDirectory ? displayName(path.basename(directory)) : 'omniscanner');

    const metadata = { title, pages };
    if (isTopicRoot) {
      metadata.root = true;
      metadata.defaultOpen = true;
      metadata.collapsible = false;
    } else if (legacyCategory.collapsed === false) {
      metadata.defaultOpen = true;
    }

    await writeFileIfChanged(
      path.join(directory, 'meta.json'),
      `${JSON.stringify(metadata, null, 2)}\n`,
    );
    generated += 1;
  }

  return generated;
}

const files = await walk(docsRoot);
const { titles: sidebarTitles, legacyCategoryRoutes } = await readSidebarConfiguration();
const documentResult = await migrateDocuments(files);
const metadataFiles = await generateMetadata(files, sidebarTitles);
await writeFileIfChanged(
  path.join(workspace, 'lib', 'legacy-category-routes.json'),
  `${JSON.stringify(legacyCategoryRoutes, null, 2)}\n`,
);

console.log(
  JSON.stringify(
    {
      ...documentResult,
      metadataFiles,
      tutorialRoots: sidebarTitles.size,
      legacyCategoryRoutes: Object.keys(legacyCategoryRoutes).length,
    },
    null,
    2,
  ),
);
